spring:
  profiles:
    active: local # 기본 환경 선택
  datasource:
    hikari:
      driver:
        class:
          name:ddddddd
        jdbc:ddddddd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

pebble:
  suffix: .html
  cache: false
  exposeSessionAttributes: true
  exposeRequestAttributes: true




  spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
  spring.datasource.hikari.jdbc-url=jdbc:mysql://{url}:{port}/{db}
  spring.datasource.hikari.username={id}
  spring.datasource.hikari.password={password}