spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_sk_6BYq7GWPVvNAyNwM7eJ5VNE5vbo1
    url: https://api.tosspayments.com